### ISSUE TITLE
Just use phpexperts/dockerize

### ISSUE THREAD

**Issue by hopeseekr** [a2way-com/drop-in-docker-php#1]
```
composer require --dev phpexperts/dockerize
php vendor/phpexperts/dockerize/install.php
```

done.

**Comment by budhajeewa** [comment]
@hopeseekr To use that, you need to have PHP and composer installed on your machine. Why Dockerize your dev environment, if you already have those installed on your host machine?

**Comment by Kreyu** [comment]
@hopeseekr What a weird way to advertise a package.

**Comment by budhajeewa** [comment]
I am closing this as there's no response from @hopeseekr . I have the vague feeling (I am probably wrong.), that he just wanted to spam with his "product".
